{
  "comments": [
    {
      "key": {
        "uuid": "9a3d3df0_00bf00ab",
        "filename": "moon_wrapper/tests/unit_python/api/test_wrapper.py",
        "patchSetId": 1
      },
      "lineNbr": 9,
      "author": {
        "id": 1384
      },
      "writtenOn": "2018-01-08T13:24:59Z",
      "side": 1,
      "message": "The interface pod has been renamed to \"pipeline\", please check that your code is up-to-date and give me the whole pytest error.",
      "range": {
        "startLine": 9,
        "startChar": 33,
        "endLine": 9,
        "endChar": 41
      },
      "revId": "57ce7daa0874c9ca7225eed940a5598848d3cf6a",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9a3d3df0_aac54e8f",
        "filename": "moon_wrapper/tests/unit_python/api/test_wrapper.py",
        "patchSetId": 1
      },
      "lineNbr": 9,
      "author": {
        "id": 7131
      },
      "writtenOn": "2018-01-09T08:15:18Z",
      "side": 1,
      "message": "def get_pickled_context():\n\u003e       from python_moonutilities.security_functions import Context\nE       ImportError: cannot import name \u0027Context\u0027\n\n\n\nthen\n\n\u003e       assert req.status_code \u003d\u003d 200\nE       assert 404 \u003d\u003d 200\nE        +  where 404 \u003d \u003cResponse streamed [404 NOT FOUND]\u003e.status_code",
      "parentUuid": "9a3d3df0_00bf00ab",
      "range": {
        "startLine": 9,
        "startChar": 33,
        "endLine": 9,
        "endChar": 41
      },
      "revId": "57ce7daa0874c9ca7225eed940a5598848d3cf6a",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9a3d3df0_8a496a33",
        "filename": "moon_wrapper/tests/unit_python/api/test_wrapper.py",
        "patchSetId": 1
      },
      "lineNbr": 9,
      "author": {
        "id": 7131
      },
      "writtenOn": "2018-01-09T08:20:44Z",
      "side": 1,
      "message": "api\\test_wrapper.py:24: AssertionError",
      "parentUuid": "9a3d3df0_aac54e8f",
      "range": {
        "startLine": 9,
        "startChar": 33,
        "endLine": 9,
        "endChar": 41
      },
      "revId": "57ce7daa0874c9ca7225eed940a5598848d3cf6a",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9a3d3df0_0a655ab4",
        "filename": "moon_wrapper/tests/unit_python/api/test_wrapper.py",
        "patchSetId": 1
      },
      "lineNbr": 9,
      "author": {
        "id": 1384
      },
      "writtenOn": "2018-01-09T08:27:03Z",
      "side": 1,
      "message": "I don\u0027t know what is your test procedure but you need to update the python_moonutilities library (pip install python_moonutilities --upgrade) either in your local configuration either in your VM. If you use the docker wukongsun/moon_python_unit_test, please use the \"latest\" tag. This should resolve your problem.",
      "parentUuid": "9a3d3df0_8a496a33",
      "range": {
        "startLine": 9,
        "startChar": 33,
        "endLine": 9,
        "endChar": 41
      },
      "revId": "57ce7daa0874c9ca7225eed940a5598848d3cf6a",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9a3d3df0_2a913e47",
        "filename": "moon_wrapper/tests/unit_python/api/test_wrapper.py",
        "patchSetId": 1
      },
      "lineNbr": 9,
      "author": {
        "id": 7131
      },
      "writtenOn": "2018-01-09T09:51:47Z",
      "side": 1,
      "message": "- i pull the latest code from git \n- then install python_moonutilities [1.4.5]\n- then ran the wrapper unit tests locally\n- it fails with the mentioned issue \n     1- import issue\n     2- [try to fix] appeared the second issue 404",
      "parentUuid": "9a3d3df0_0a655ab4",
      "range": {
        "startLine": 9,
        "startChar": 33,
        "endLine": 9,
        "endChar": 41
      },
      "revId": "57ce7daa0874c9ca7225eed940a5598848d3cf6a",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    },
    {
      "key": {
        "uuid": "9a3d3df0_4a38023d",
        "filename": "moon_wrapper/tests/unit_python/api/test_wrapper.py",
        "patchSetId": 1
      },
      "lineNbr": 9,
      "author": {
        "id": 1384
      },
      "writtenOn": "2018-01-09T10:24:48Z",
      "side": 1,
      "message": "I made a mistake when moving from \"interface\" to \"pipeline\", a patch will follow",
      "parentUuid": "9a3d3df0_2a913e47",
      "range": {
        "startLine": 9,
        "startChar": 33,
        "endLine": 9,
        "endChar": 41
      },
      "revId": "57ce7daa0874c9ca7225eed940a5598848d3cf6a",
      "serverId": "bbac25d2-bf60-4904-9ba8-a72fc000d6c5",
      "unresolved": false
    }
  ]
}